# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_github_packages: 
  psobczyk/pesel
before_install:
  - R -e 'source("https://bioconductor.org/biocLite.R"); biocLite("impute")'
r:
  - release
  - devel
